# Generated by Django 3.0.4 on 2020-03-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_auto_20200313_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamemployee',
            name='added_at',
        ),
        migrations.AddField(
            model_name='employee',
            name='is_a_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamemployee',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
