# Generated by Django 3.0.4 on 2020-03-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_auto_20200315_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workarrangement',
            old_name='description',
            new_name='remarks',
        ),
    ]
