# Generated by Django 3.0.4 on 2020-03-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_auto_20200315_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workarrangement',
            old_name='percentage',
            new_name='percent',
        ),
    ]
