# Generated by Django 3.0.4 on 2020-03-18 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_auto_20200318_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamEmployee', to='backend_api.Employee'),
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamLeaader', to='backend_api.Employee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_api.Team')),
            ],
        ),
    ]
