# Generated by Django 3.0.4 on 2020-03-20 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0010_auto_20200319_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='workarrangement',
            name='team',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='backend_api.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worktime',
            name='work_arrangement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_api.WorkArrangement'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
