# Generated by Django 3.0.4 on 2020-03-22 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0012_auto_20200320_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 16, 24, 2, 408750)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 16, 24, 2, 408750)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 16, 24, 2, 408750)),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 16, 24, 2, 408750)),
        ),
        migrations.AlterField(
            model_name='teamemployee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 16, 24, 2, 408750)),
        ),
        migrations.AlterField(
            model_name='teamemployee',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 16, 24, 2, 408750)),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 16, 24, 2, 408750)),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 16, 24, 2, 408750)),
        ),
    ]
