# Generated by Django 3.0.4 on 2020-03-24 12:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0013_auto_20200322_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 20, 51, 21, 797147)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 20, 51, 21, 797147)),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 20, 51, 21, 797147)),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 20, 51, 21, 797147)),
        ),
        migrations.AlterField(
            model_name='teamemployee',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 20, 51, 21, 798147)),
        ),
        migrations.AlterField(
            model_name='teamemployee',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 20, 51, 21, 798147)),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 20, 51, 21, 798147)),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend_api.Team'),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 20, 51, 21, 798147)),
        ),
    ]
